//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPadelApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPadelApp.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept all the required terms and conditions, privacy policy, and marketing preferences..
        /// </summary>
        internal static string AcceptConditions {
            get {
                return ResourceManager.GetString("AcceptConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the terms and conditions..
        /// </summary>
        internal static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the Terms and Conditions.
        /// </summary>
        internal static string AcceptTermsText {
            get {
                return ResourceManager.GetString("AcceptTermsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to MyPadel to challenge your friends and improve your score!.
        /// </summary>
        internal static string AccessText {
            get {
                return ResourceManager.GetString("AccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Cancellation.
        /// </summary>
        internal static string AccountCancellation {
            get {
                return ResourceManager.GetString("AccountCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been deleted successfully.
        /// </summary>
        internal static string AccountDeleted {
            get {
                return ResourceManager.GetString("AccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card.
        /// </summary>
        internal static string AddCard {
            get {
                return ResourceManager.GetString("AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressPlaceholder {
            get {
                return ResourceManager.GetString("AddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required..
        /// </summary>
        internal static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re almost there!.
        /// </summary>
        internal static string AlmostThere {
            get {
                return ResourceManager.GetString("AlmostThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARCHIVED.
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention to expiration!.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking “Confirm Account Deletion,” your account will be deleted. To use the app again, you must re-register!.
        /// </summary>
        internal static string AttentionDescription {
            get {
                return ResourceManager.GetString("AttentionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        internal static string AttentionTitle {
            get {
                return ResourceManager.GetString("AttentionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  the start of the first game to register your.
        /// </summary>
        internal static string BeforeGameStart {
            get {
                return ResourceManager.GetString("BeforeGameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string BookButton {
            get {
                return ResourceManager.GetString("BookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book a camp.
        /// </summary>
        internal static string BookFieldButton {
            get {
                return ResourceManager.GetString("BookFieldButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your booking has been cancelled successfully.
        /// </summary>
        internal static string BookingCanceled {
            get {
                return ResourceManager.GetString("BookingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string BookingDate {
            get {
                return ResourceManager.GetString("BookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string BookingDuration {
            get {
                return ResourceManager.GetString("BookingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string BookingPrice {
            get {
                return ResourceManager.GetString("BookingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Status.
        /// </summary>
        internal static string BookingStatus {
            get {
                return ResourceManager.GetString("BookingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string BookingStatusValue {
            get {
                return ResourceManager.GetString("BookingStatusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riepilogo prenotazione.
        /// </summary>
        internal static string BookingSummary {
            get {
                return ResourceManager.GetString("BookingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Summary.
        /// </summary>
        internal static string BookingSummaryTitle {
            get {
                return ResourceManager.GetString("BookingSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string BookingTime {
            get {
                return ResourceManager.GetString("BookingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string BookText {
            get {
                return ResourceManager.GetString("BookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , call us and present yourself.
        /// </summary>
        internal static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padel Field .
        /// </summary>
        internal static string CampoPadel {
            get {
                return ResourceManager.GetString("CampoPadel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Padel 2.
        /// </summary>
        internal static string CampoPadel2 {
            get {
                return ResourceManager.GetString("CampoPadel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel reservation.
        /// </summary>
        internal static string CancelBookingButton {
            get {
                return ResourceManager.GetString("CancelBookingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cancel the booking within 24 hours in advance using the application, then you will necessarily have to call the centre.
        /// </summary>
        internal static string CancellationDescription {
            get {
                return ResourceManager.GetString("CancellationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrai disdire la prenotazione entro 24 ore prima utilizzando l’applicazione, successivamente dovrai necessariamente chiamare il centro.
        /// </summary>
        internal static string CancellationDetails {
            get {
                return ResourceManager.GetString("CancellationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Policy.
        /// </summary>
        internal static string CancellationPolicy {
            get {
                return ResourceManager.GetString("CancellationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can cancel up to 24 hours before your booking..
        /// </summary>
        internal static string CancellationText {
            get {
                return ResourceManager.GetString("CancellationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL RESERVATION SCREEN
        /// + 
        ///REFUND.
        /// </summary>
        internal static string CancelScreenDescription {
            get {
                return ResourceManager.GetString("CancelScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        internal static string CardNumberPlaceholder {
            get {
                return ResourceManager.GetString("CardNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is required..
        /// </summary>
        internal static string CardNumberRequired {
            get {
                return ResourceManager.GetString("CardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always check that you have an active medical certificate, without it you won’t be able to play..
        /// </summary>
        internal static string CertificateDescription {
            get {
                return ResourceManager.GetString("CertificateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beware of the expiration!.
        /// </summary>
        internal static string CertificateReminder {
            get {
                return ResourceManager.GetString("CertificateReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always make sure you have the.
        /// </summary>
        internal static string CheckCard {
            get {
                return ResourceManager.GetString("CheckCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        internal static string ChooseDuration {
            get {
                return ResourceManager.GetString("ChooseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string CityPlaceholder {
            get {
                return ResourceManager.GetString("CityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information.
        /// </summary>
        internal static string CompanyInformation {
            get {
                return ResourceManager.GetString("CompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of this .
        /// </summary>
        internal static string ConditionsTermsText {
            get {
                return ResourceManager.GetString("ConditionsTermsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  the terms and conditions .
        /// </summary>
        internal static string ConditionsText {
            get {
                return ResourceManager.GetString("ConditionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Account Deletion.
        /// </summary>
        internal static string ConfirmButtonText {
            get {
                return ResourceManager.GetString("ConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Code.
        /// </summary>
        internal static string ConfirmCode {
            get {
                return ResourceManager.GetString("ConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Code.
        /// </summary>
        internal static string ConfirmCodeButton {
            get {
                return ResourceManager.GetString("ConfirmCodeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        internal static string ConfirmNewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password...
        /// </summary>
        internal static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required..
        /// </summary>
        internal static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padel field 2.
        /// </summary>
        internal static string CourtName {
            get {
                return ResourceManager.GetString("CourtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court.
        /// </summary>
        internal static string CourtPadel {
            get {
                return ResourceManager.GetString("CourtPadel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string CreateAccountButton {
            get {
                return ResourceManager.GetString("CreateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carta di credito / Bancomat.
        /// </summary>
        internal static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Credit card / ATM.
        /// </summary>
        internal static string CreditCardMethod {
            get {
                return ResourceManager.GetString("CreditCardMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string CreditCardPayment {
            get {
                return ResourceManager.GetString("CreditCardPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cricket.
        /// </summary>
        internal static string Cricket {
            get {
                return ResourceManager.GetString("Cricket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password...
        /// </summary>
        internal static string CurrentPasswordPlaceholder {
            get {
                return ResourceManager.GetString("CurrentPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Certificate Expiration Date.
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth (dd-mm-yyyy).
        /// </summary>
        internal static string DateofBrithPlaceholder {
            get {
                return ResourceManager.GetString("DateofBrithPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETED.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address and password.
        /// </summary>
        internal static string EmailPasswordInstruction {
            get {
                return ResourceManager.GetString("EmailPasswordInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address...
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email OTP has been resent successfully.
        /// </summary>
        internal static string EmailResent {
            get {
                return ResourceManager.GetString("EmailResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your details below..
        /// </summary>
        internal static string EnterDetails {
            get {
                return ResourceManager.GetString("EnterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter lastname.
        /// </summary>
        internal static string EnterSurname {
            get {
                return ResourceManager.GetString("EnterSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date must be in the future..
        /// </summary>
        internal static string ExpiryDateRequired {
            get {
                return ResourceManager.GetString("ExpiryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to capture photo..
        /// </summary>
        internal static string FailCapturePhoto {
            get {
                return ResourceManager.GetString("FailCapturePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final step!.
        /// </summary>
        internal static string FinalStepHeading {
            get {
                return ResourceManager.GetString("FinalStepHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIT Card.
        /// </summary>
        internal static string FitCard {
            get {
                return ResourceManager.GetString("FitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active FIT card,.
        /// </summary>
        internal static string FITCardActive {
            get {
                return ResourceManager.GetString("FITCardActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIT Card.
        /// </summary>
        internal static string FitCardLabel {
            get {
                return ResourceManager.GetString("FitCardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string GenderPlaceholder {
            get {
                return ResourceManager.GetString("GenderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender must be selected.
        /// </summary>
        internal static string GenderSelected {
            get {
                return ResourceManager.GetString("GenderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already have a FIT card. Please arrive 20 minutes early before your first match to register your FIT card..
        /// </summary>
        internal static string HasCardInstruction {
            get {
                return ResourceManager.GetString("HasCardInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already have a FIT card. We recommend arriving.
        /// </summary>
        internal static string HaveFITCard {
            get {
                return ResourceManager.GetString("HaveFITCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Certificate.
        /// </summary>
        internal static string HealthCertificate {
            get {
                return ResourceManager.GetString("HealthCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help and contacts.
        /// </summary>
        internal static string HelpsContact {
            get {
                return ResourceManager.GetString("HelpsContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///•Identity card.
        /// </summary>
        internal static string IdentityCard {
            get {
                return ResourceManager.GetString("IdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User consent to the processing of data for promotional purposes.
        /// </summary>
        internal static string Image2Text {
            get {
                return ResourceManager.GetString("Image2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your FIT card. Without it, you cannot play. If you don&apos;t have one, we can register it for you..
        /// </summary>
        internal static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Brith Date.
        /// </summary>
        internal static string InvalidBrithDate {
            get {
                return ResourceManager.GetString("InvalidBrithDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number must be 16 digits long..
        /// </summary>
        internal static string Invalidcardnumber {
            get {
                return ResourceManager.GetString("Invalidcardnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical certificate date cannot be in the future..
        /// </summary>
        internal static string InvalidCertificateDate {
            get {
                return ResourceManager.GetString("InvalidCertificateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Italian phone number format. Example of valid formats:\n- Landline: +39 06 1234567 (Rome)\n- Mobile: +39 345 1234567.
        /// </summary>
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code must be numeric and 5-10 characters long..
        /// </summary>
        internal static string Invalidpostalcode {
            get {
                return ResourceManager.GetString("Invalidpostalcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Arrow.
        /// </summary>
        internal static string LeftArrow {
            get {
                return ResourceManager.GetString("LeftArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGO.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGO.
        /// </summary>
        internal static string LogoText {
            get {
                return ResourceManager.GetString("LogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match History.
        /// </summary>
        internal static string MatchHistory {
            get {
                return ResourceManager.GetString("MatchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match History.
        /// </summary>
        internal static string MatchHistoryPageTitle {
            get {
                return ResourceManager.GetString("MatchHistoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the start of the match.
        /// </summary>
        internal static string MatchStart {
            get {
                return ResourceManager.GetString("MatchStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///•Medical Certificate.
        /// </summary>
        internal static string MedicalCertificate {
            get {
                return ResourceManager.GetString("MedicalCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical certificate date is required..
        /// </summary>
        internal static string MedicalCertificateDateRequired {
            get {
                return ResourceManager.GetString("MedicalCertificateDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical certificate is required..
        /// </summary>
        internal static string MedicalCertificateRequired {
            get {
                return ResourceManager.GetString("MedicalCertificateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email you registered with on MyPadel. We&apos;ll send you an OTP code via SMS to the phone number you registered with..
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120 min.
        /// </summary>
        internal static string Min120 {
            get {
                return ResourceManager.GetString("Min120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 min.
        /// </summary>
        internal static string Min60 {
            get {
                return ResourceManager.GetString("Min60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 min.
        /// </summary>
        internal static string Min90 {
            get {
                return ResourceManager.GetString("Min90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string MonthName {
            get {
                return ResourceManager.GetString("MonthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        internal static string MunicipalityPlaceholder {
            get {
                return ResourceManager.GetString("MunicipalityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality is required..
        /// </summary>
        internal static string MunicipalityRequried {
            get {
                return ResourceManager.GetString("MunicipalityRequried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Last.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Policy.
        /// </summary>
        internal static string NewCancellationPolicy {
            get {
                return ResourceManager.GetString("NewCancellationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game to play.
        /// </summary>
        internal static string NewText {
            get {
                return ResourceManager.GetString("NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don’t have a FIT card. Please arrive 30 minutes early with:
        ///• ID card
        ///• Medical Certificate
        ///To register your new FIT card..
        /// </summary>
        internal static string NoCardInstruction {
            get {
                return ResourceManager.GetString("NoCardInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data found.
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file chosen..
        /// </summary>
        internal static string NoFileChosen {
            get {
                return ResourceManager.GetString("NoFileChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t have a FIT card. We recommend that you pass.
        /// </summary>
        internal static string NoFITCard {
            get {
                return ResourceManager.GetString("NoFITCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture is not supported on this device..
        /// </summary>
        internal static string NotSupportedCamera {
            get {
                return ResourceManager.GetString("NotSupportedCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of them must be selected.
        /// </summary>
        internal static string OneSelected {
            get {
                return ResourceManager.GetString("OneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string OrLabel {
            get {
                return ResourceManager.GetString("OrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is requried.
        /// </summary>
        internal static string OTPRequired {
            get {
                return ResourceManager.GetString("OTPRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PADEL.
        /// </summary>
        internal static string Padel {
            get {
                return ResourceManager.GetString("Padel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PADEL.
        /// </summary>
        internal static string PadelCourt {
            get {
                return ResourceManager.GetString("PadelCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PADEL COURT 1.
        /// </summary>
        internal static string PadelCourt1 {
            get {
                return ResourceManager.GetString("PadelCourt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PADEL COURT 2.
        /// </summary>
        internal static string PadelCourt2 {
            get {
                return ResourceManager.GetString("PadelCourt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padel.
        /// </summary>
        internal static string PadelLabel {
            get {
                return ResourceManager.GetString("PadelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padel.
        /// </summary>
        internal static string PadelText {
            get {
                return ResourceManager.GetString("PadelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLoginPlaceholder {
            get {
                return ResourceManager.GetString("PasswordLoginPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e-mail address and password.
        /// </summary>
        internal static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is requried.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must include an uppercase letter, a lowercase letter, a number, a special character, and be at least 6 characters long..
        /// </summary>
        internal static string PasswordStrengthRequired {
            get {
                return ResourceManager.GetString("PasswordStrengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been updated successfully.
        /// </summary>
        internal static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string PayButtonText {
            get {
                return ResourceManager.GetString("PayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method:.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method:.
        /// </summary>
        internal static string PaymentMethodHeading {
            get {
                return ResourceManager.GetString("PaymentMethodHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentMethod must be selected.
        /// </summary>
        internal static string PaymentMethodSelected {
            get {
                return ResourceManager.GetString("PaymentMethodSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Cash.
        /// </summary>
        internal static string PaymentOptionCash {
            get {
                return ResourceManager.GetString("PaymentOptionCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Credit card / Debit card.
        /// </summary>
        internal static string PaymentOptionCreditCard {
            get {
                return ResourceManager.GetString("PaymentOptionCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • PayPal.
        /// </summary>
        internal static string PaymentOptionPayPal {
            get {
                return ResourceManager.GetString("PaymentOptionPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Satispay.
        /// </summary>
        internal static string PaymentOptionSatispay {
            get {
                return ResourceManager.GetString("PaymentOptionSatispay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Screen.
        /// </summary>
        internal static string PaymentScreenTitle {
            get {
                return ResourceManager.GetString("PaymentScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paga Online.
        /// </summary>
        internal static string PayOnline {
            get {
                return ResourceManager.GetString("PayOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        internal static string PayPal {
            get {
                return ResourceManager.GetString("PayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera or Storage permission not granted.
        /// </summary>
        internal static string PermissionNotGranted {
            get {
                return ResourceManager.GetString("PermissionNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number, we&apos;ll send you a code to verify your contact..
        /// </summary>
        internal static string PhoneNumberPrompt {
            get {
                return ResourceManager.GetString("PhoneNumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is required..
        /// </summary>
        internal static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone OTP has been resent successfully.
        /// </summary>
        internal static string PhoneResent {
            get {
                return ResourceManager.GetString("PhoneResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code is required..
        /// </summary>
        internal static string PostalCodeRequired {
            get {
                return ResourceManager.GetString("PostalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy..
        /// </summary>
        internal static string PrivacyText {
            get {
                return ResourceManager.GetString("PrivacyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to payment.
        /// </summary>
        internal static string ProceedPayment {
            get {
                return ResourceManager.GetString("ProceedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Information.
        /// </summary>
        internal static string ProfileInfoLabel {
            get {
                return ResourceManager.GetString("ProfileInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Information.
        /// </summary>
        internal static string ProfileInformation {
            get {
                return ResourceManager.GetString("ProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Information.
        /// </summary>
        internal static string ProfileInformationPageTitle {
            get {
                return ResourceManager.GetString("ProfileInformationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you already have a FIT card?.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready to play?.
        /// </summary>
        internal static string ReadyToPlayText {
            get {
                return ResourceManager.GetString("ReadyToPlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        internal static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIT card..
        /// </summary>
        internal static string RegisterFITCard {
            get {
                return ResourceManager.GetString("RegisterFITCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///To register your new FIT card..
        /// </summary>
        internal static string RegisterNewFITCard {
            get {
                return ResourceManager.GetString("RegisterNewFITCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the details below to create your FIT card..
        /// </summary>
        internal static string RegistrationDescription {
            get {
                return ResourceManager.GetString("RegistrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick it up at the front desk before you start playing!.
        /// </summary>
        internal static string RegistrationFooter {
            get {
                return ResourceManager.GetString("RegistrationFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll register you!.
        /// </summary>
        internal static string RegistrationHeading {
            get {
                return ResourceManager.GetString("RegistrationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you need to renew it.
        /// </summary>
        internal static string RenewIt {
            get {
                return ResourceManager.GetString("RenewIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request new card.
        /// </summary>
        internal static string RequestNewCard {
            get {
                return ResourceManager.GetString("RequestNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-send email.
        /// </summary>
        internal static string ReSendButton {
            get {
                return ResourceManager.GetString("ReSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send new code.
        /// </summary>
        internal static string ResendCode {
            get {
                return ResourceManager.GetString("ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        internal static string ResendCodeText {
            get {
                return ResourceManager.GetString("ResendCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the link we sent you via email to confirm your registration!.
        /// </summary>
        internal static string ResendemailMessage {
            get {
                return ResourceManager.GetString("ResendemailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email...
        /// </summary>
        internal static string ResetEmailPlaceholder {
            get {
                return ResourceManager.GetString("ResetEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password.
        /// </summary>
        internal static string ResetNewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ResetNewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Arrow.
        /// </summary>
        internal static string RightArrow {
            get {
                return ResourceManager.GetString("RightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satispay.
        /// </summary>
        internal static string Satispay {
            get {
                return ResourceManager.GetString("Satispay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen with list of linked cards or PayPal account.
        /// </summary>
        internal static string ScreenTitle {
            get {
                return ResourceManager.GetString("ScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Field.
        /// </summary>
        internal static string SearchField {
            get {
                return ResourceManager.GetString("SearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy information.
        /// </summary>
        internal static string SecurityLabel {
            get {
                return ResourceManager.GetString("SecurityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli la durata.
        /// </summary>
        internal static string SelectDuration {
            get {
                return ResourceManager.GetString("SelectDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Code.
        /// </summary>
        internal static string SendCode {
            get {
                return ResourceManager.GetString("SendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Code.
        /// </summary>
        internal static string SendCodeButton {
            get {
                return ResourceManager.GetString("SendCodeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soccer.
        /// </summary>
        internal static string SoccerText {
            get {
                return ResourceManager.GetString("SoccerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wents wrong.
        /// </summary>
        internal static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        internal static string SportLabel {
            get {
                return ResourceManager.GetString("SportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        internal static string SportText {
            get {
                return ResourceManager.GetString("SportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string StatusAvailable {
            get {
                return ResourceManager.GetString("StatusAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked.
        /// </summary>
        internal static string StatusBooked {
            get {
                return ResourceManager.GetString("StatusBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        internal static string SurnamePlaceholder {
            get {
                return ResourceManager.GetString("SurnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname is required..
        /// </summary>
        internal static string SurnameRequired {
            get {
                return ResourceManager.GetString("SurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis.
        /// </summary>
        internal static string TennisLabel {
            get {
                return ResourceManager.GetString("TennisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis.
        /// </summary>
        internal static string TennisText {
            get {
                return ResourceManager.GetString("TennisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and condition must be agreed.
        /// </summary>
        internal static string TermsAndConditionAgree {
            get {
                return ResourceManager.GetString("TermsAndConditionAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By registering, you accept.
        /// </summary>
        internal static string TermsText {
            get {
                return ResourceManager.GetString("TermsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes before.
        /// </summary>
        internal static string ThirtyMinutesBefore {
            get {
                return ResourceManager.GetString("ThirtyMinutesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already FIT Card.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 minutes before.
        /// </summary>
        internal static string TwentyMinutesBefore {
            get {
                return ResourceManager.GetString("TwentyMinutesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        internal static string UpdatePasswordButton {
            get {
                return ResourceManager.GetString("UpdatePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload medical certificate.
        /// </summary>
        internal static string UploadMedicalCertificate {
            get {
                return ResourceManager.GetString("UploadMedicalCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your details have been entered correctly!
        ///
        ///We are verifying the correctness of your details!
        ///
        ///If the details entered are correct, you will receive a notification and you will be able to track the expiry of your FIT card directly from the app!
        ///
        ///Remember to renew your card before it expires, access the &quot;FIT card&quot; section from &quot;My profile&quot; starting 30 days before the expiry date..
        /// </summary>
        internal static string VerificationMessage {
            get {
                return ResourceManager.GetString("VerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to My Padel App!.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When do you want to play?.
        /// </summary>
        internal static string WhenDoYouWantToPlay {
            get {
                return ResourceManager.GetString("WhenDoYouWantToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When do you want to play?.
        /// </summary>
        internal static string WhenYouWantToPlay {
            get {
                return ResourceManager.GetString("WhenYouWantToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which time slot do you want to play?.
        /// </summary>
        internal static string WhichTimeSlotToPlay {
            get {
                return ResourceManager.GetString("WhichTimeSlotToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with:.
        /// </summary>
        internal static string With {
            get {
                return ResourceManager.GetString("With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP code.
        /// </summary>
        internal static string ZipCodePlaceholder {
            get {
                return ResourceManager.GetString("ZipCodePlaceholder", resourceCulture);
            }
        }
    }
}
